### ISSUE TITLE
Create toggle for instances running over https

### ISSUE THREAD

**Issue by derickwarshaw** [derickwarshaw/jenkins#13]
This toggle should update the axios defaultURL. The toggle should be located somewhere near the fields the user uses to enter instance information.

**Comment by triedal** [comment]
I'll take a stab at this one.

**Comment by derickwarshaw** [comment]
Nice! An idea you could marinate on or build from would be to get a toggle component and have it set a flag in state/redux that would get passed to startLogin() at the Service/Api.js level. From there based on the flag the default base url could be modified for http/https.
