### ISSUE TITLE
Update App Icon

### ISSUE THREAD

**Issue by derickwarshaw** [derickwarshaw/jenkins#5]
It would be nice to see some cool ideas on the app icon. The one currently in place was just a quick one I threw together from an existing Jenkins logo. It would be cool to see something original.

**Comment by pv2k** [comment]
i can help you, by suggesting some new icons.

**Comment by pv2k** [comment]
but i am not able to install genymotion in my ubuntu 16.04, so, if possible, please send me the icon of your app and i will get back with some cool ideas.
