### ISSUE TITLE
Add Resources Documentation

### ISSUE THREAD

**Issue by nicholas-b-carter** [derickwarshaw/jenkins#52]

**Comment by jotasprout** [comment]
Any more guidance available? If I run the app locally, will the nature of "Resources" be obvious enough that I could just start writing documentation for it?

**Comment by derickwarshaw** [comment]
With better use of esdocs in the API/Services area as well as the app as a whole - this would likely be resolved with the integration of github pages and our parsed documentation. Closing for now and will open individual issues related to documenting the app for specific areas of need.
