### ISSUE TITLE
Write Unit Test: LoginReducer.js

### ISSUE THREAD

**Issue by derickwarshaw** [derickwarshaw/jenkins#63]
Using Ava - write UT for LoginReducer.js

**Comment by csham** [comment]
@derickwarshaw looks like LoginReducerTest.js already exists and is reporting 100% with `npm run coverage`.  Let me know if there is something in particular that needs to be done for this.

**Comment by derickwarshaw** [comment]
Good call! Looks like this was closed by #80 courtesy of you! Thanks!
