### ISSUE TITLE
Combine button components

### ISSUE THREAD

**Issue by bbohen** [derickwarshaw/jenkins#72]
It looks like `DrawerButton`, `FullButton` and `RoundedButton` could be combined into one component as the structure of all three is

```
<TouchableOpacity>
    <Text>Some Text</Text>
</TouchableOpacity>
```

I could be off here and each of these buttons may have a very specific purpose or there could be plans to expand these guys.

**Comment by Daadler6** [comment]
I'll look into this one as well as making them stateless

**Comment by triedal** [comment]
@derickwarshaw FullButton is not used in the project. Do we need it?
