### ISSUE TITLE
Hook up build server for linting/test running on PR

### ISSUE THREAD

**Issue by derickwarshaw** [derickwarshaw/jenkins#8]
Arrange for a Jenkins job to run linting/tests and report back pass/fail on PR submit.

**Comment by unsaturated** [comment]
I haven't personally used it but [Travis CI](https://travis-ci.org/) looks like a good fit.
<img width="828" alt="travis-ci" src="https://cloud.githubusercontent.com/assets/284259/18609449/71405348-7cd0-11e6-818d-2bd86bfbb513.png">

**Comment by derickwarshaw** [comment]
I haven't used Travis either but it might be fun to set it up. I have a Jenkins server set up at the moment to handle this I just need to set up the job and add a script. I'll have it ready this weekend once the eslint integration branch gets merged in. Tests would be next...

**Comment by derickwarshaw** [comment]
Integrated with Jenkins server to build and lint. Creating separate issue for test running.
